### PR TITLE
Initial documentation

### PR DESCRIPTION
**Pull request by mmiller-max**
Testing deployment.

Also will close when #36  and #34 are sorted to avoid having to redo docs.

### CODE REVIEW

**Comment by mmiller-max** [comment]
Hey @oxinabox , I'd like to setup the normal documents for TestReports, but don't have the permissions to add the public key to the repo as per https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#travis-ssh. (I can add the private key to Travis).

Would it please be possible for me to be granted the permission or for you to do the ssh step?

Cheers

**Comment by oxinabox** [comment]
I have upped your permissions to Owner

**Review by oxinabox — APPROVED** [review]
These look good, I am sure the final product will also be good

**Comment by mmiller-max** [comment]
Cheers! Feel free to check it out at https://juliatesting.github.io/TestReports.jl/previews/PR37/manual/

Any feedback welcome, especially on the logo...

**Comment by mmiller-max** [comment]
Will also close #39

**Pull request merged**
