### PR TITLE
Pretty formatted XML

### PR DESCRIPTION
**Pull request by omus**
After working on this package for a while I think the reference tests would be better if we used pretty formatted XML as it makes it more obvious what's wrong in the reference test diff. The counter argument to this is that this re-order the attributes from what users get out of the box without pretty printing.

Depends on:
- #106

### CODE REVIEW

**Comment by oxinabox** [comment]
Can we change to always pretty printing? That would make these tests consistent with the actual behavour users see.
And would also generally be a improvement for most users i think.
It would be good to get this in as part of 1.0

That would be changing the `write` to be a `open` + `prettyprint`
https://github.com/JuliaTesting/TestReports.jl/blob/98ffbf06e6f8600b65cb79d9cb15e9a42e4030bb/src/runner.jl#L140

**Review by oxinabox — APPROVED** [review]
Approving this, as i don't think you need further feedback beyond the comment i gave above before this is mergable

**Comment by omus** [comment]
> Can we change to always pretty printing? That would make these tests consistent with the actual behavour users see. And would also generally be a improvement for most users i think. It would be good to get this in as part of 1.0
> 
> That would be changing the `write` to be a `open` + `prettyprint`
> 
> https://github.com/JuliaTesting/TestReports.jl/blob/98ffbf06e6f8600b65cb79d9cb15e9a42e4030bb/src/runner.jl#L140

Sounds good. I do like have the option of having compact printing so maybe I'll look into having an keyword for this.

**Comment by omus** [comment]
> I do like have the option of having compact printing so maybe I'll look into having an keyword for this.

I still think this is a good idea but is more additional work I don't want to take on at this time. As the users can use `report` directly and render the XML structure however they want I think this is less of an issue than I first thought.

**Pull request merged**
