### PR TITLE
Wrapped <error> tag in a <testcase> for XML output

### LINKED ISSUE #97: Incorrect JUnit XML for error outside of test case
I encountered an issue trying to convert JUnit XML output from TestReports.jl to html using any package. None of them were displayed the result from an exception being thrown.

I couldn't find a clear definition for what the XML format is supposed to be, but I believe the <error> element needs to be wrapped in a <testcase> element for other packages to parse it correctly.

Below, I have example tests that throw errors and my proposed fix.

```julia
using Test
using TestReports

# Current behavior
ts = @testset ReportingTestSet "" begin
    @testset "Normal tests" begin
        @test true
        @test false
    end
    @testset "Error inside test" begin
        @test true
        @test false
        @test doesntexist == 1
    end
    @testset "Error outside test" begin
        @test true
        @test false
        a = doesntexist
    end
end
println("This XML puts <error> as direct children of <testsuite>")
TestReports.EzXML.prettyprint(report(ts))


# Update to put error result inside a test case.
function TestReports.to_xml(v::TestReports.Error)
    message, type, ntest = TestReports.get_error_info(v)
    x_error = TestReports.error_xml(message, type, v.backtrace)
    x_testcase = TestReports.testcase_xml(v, [x_error])
    x_testcase, ntest, 0, 1  # Increment number of errors by 1
end

ts = @testset ReportingTestSet "" begin
    @testset "Normal tests" begin
        @test true
        @test false
    end
    @testset "Error inside test" begin
        @test true
        @test false
        @test doesntexist == 1
    end
    @testset "Error outside test" begin
        @test true
        @test false
        a = doesntexist
    end
end
println("This XML puts <error> as direct children of <testcase>")
TestReports.EzXML.prettyprint(report(ts))
```

### PR DESCRIPTION
**Pull request by gbruer15**
Closes #97

### CODE REVIEW

**Comment by gbruer15** [comment]
@oxinabox This is ready to merge, other than the failing tests that are outside the scope of this MR. Can you review it.

The test on Julia 1.10 is failing, but the tests on Julia 1.0, 1.6, and 1.12-nightly are passing and locally testing on 1.8 works fine.

**Review by oxinabox — APPROVED** [review]
This looks right
 @mmiller-max did you know what is up with the failing test cases?

**Comment by omus** [comment]
Failure here should be addressed by #99

**Comment by oxinabox** [comment]
@gbruer15 can you rebase this against current master, and that should catch what was fixed in #99 and so we should be able to merge this.

**Comment by mmiller-max** [comment]
> This looks right @mmiller-max did you know what is up with the failing test cases?

Sorry I missed this. Thanks for fixing @omus

**Comment by gbruer15** [comment]
@oxinabox This is ready to merge now.

**Pull request merged**
