### PR TITLE
Define constant to `reporttests.jl`

### PR DESCRIPTION
**Pull request by omus**
Avoids making users use `joinpath(pkgdir(TestReports), "bin", "reporttests.jl")` to determine the path to the runner script.

### CODE REVIEW

**Review by oxinabox — APPROVED** [review]
We should document this.
1. by mentioning it in the readme/docs
2. by putting a docstring on the constant

Once that is done, then LGTM

**Comment by omus** [comment]
I did a patch bump here as I think it was an oversight not to have a public facing reference to the `reporttests.jl` script if we intend for users of this package to use it.

**Comment by oxinabox** [comment]
I would describe this as a new feature.
Now it is much easier for a user to make use of this.

But I am not strongly committed to that

**Comment by omus** [comment]
Okay. As #113 is uncovering a couple of minor things to fix I'll drop the version bump here and add it later on.

**Pull request merged**
